name: string_masker
description: A Flutter package for masking and validating sensitive data like emails, phone numbers, and credit cards with built-in validation.
version: 1.0.0
repository: https://github.com/eslamelezaby98/string_masker

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
